import { WorkflowNode, WorkflowEdge } from './types';
import { nodeRegistry } from './registry';

/**
 * Executes a workflow graph starting from a specific trigger node.
 * Performs a topological sort and calls handlers in the registry for each node.
 * 
 * @param nodes All nodes in the workflow
 * @param edges All edges connecting nodes
 * @param startNodeId The ID of the node that triggered the execution
 * @param initialOutputs Output data from the trigger node itself (e.g., event data)
 * @returns Map of node outputs
 */
export async function executeWorkflow(
  nodes: WorkflowNode[],
  edges: WorkflowEdge[],
  startNodeId: string,
  initialOutputs: Record<string, any> = {}
): Promise<Record<string, Record<string, any>>> {
  // Collect outputs generated by each node
  const nodeOutputs: Record<string, Record<string, any>> = {
    [startNodeId]: initialOutputs
  };

  const nodeMap = new Map<string, WorkflowNode>();
  const adjacencyList = new Map<string, string[]>();
  
  for (const node of nodes) {
    nodeMap.set(node.id, node);
    adjacencyList.set(node.id, []);
  }

  // Build the graph representing node -> children based on active nodes
  for (const edge of edges) {
    if (adjacencyList.has(edge.source) && nodeMap.has(edge.target)) {
      adjacencyList.get(edge.source)!.push(edge.target);
    }
  }

  // 1. Gather all nodes reachable from startNodeId
  const reachableNodes = new Set<string>();
  const queue = [startNodeId];
  reachableNodes.add(startNodeId);
  
  while (queue.length > 0) {
    const cur = queue.shift()!;
    for (const neighbor of adjacencyList.get(cur) || []) {
      if (!reachableNodes.has(neighbor)) {
        reachableNodes.add(neighbor);
        queue.push(neighbor);
      }
    }
  }

  // 2. Compute in-degrees for reachable subgraph only
  const inDegree = new Map<string, number>();
  for (const node of reachableNodes) {
    inDegree.set(node, 0);
  }

  for (const edge of edges) {
    if (reachableNodes.has(edge.source) && reachableNodes.has(edge.target)) {
      inDegree.set(edge.target, inDegree.get(edge.target)! + 1);
    }
  }

  // 3. Topological Sort (Kahn's Algorithm)
  const topoQueue: string[] = [];
  for (const [nodeId, degree] of inDegree.entries()) {
    if (degree === 0) {
      topoQueue.push(nodeId);
    }
  }

  const sortedNodes: string[] = [];
  while (topoQueue.length > 0) {
    const curId = topoQueue.shift()!;
    sortedNodes.push(curId);
    for (const neighbor of adjacencyList.get(curId) || []) {
      if (reachableNodes.has(neighbor)) {
        const newDegree = inDegree.get(neighbor)! - 1;
        inDegree.set(neighbor, newDegree);
        if (newDegree === 0) {
          topoQueue.push(neighbor);
        }
      }
    }
  }

  if (sortedNodes.length !== reachableNodes.size) {
    throw new Error('Cycle detected in workflow graph');
  }

  // 4. Iterate over sorted nodes and execute
  for (const nodeId of sortedNodes) {
    const node = nodeMap.get(nodeId)!;

    // Trigger node output is already provided by the caller
    if (nodeId === startNodeId) {
      continue;
    }

    // A node that is not the start node shouldn't execute if it's acting as a separate trigger
    if (node.type === 'triggerNode') {
      continue;
    }

    // Collect upstream port values
    const incomingEdges = edges.filter(e => e.target === nodeId);
    const inputs: Record<string, any> = {};

    for (const edge of incomingEdges) {
      if (nodeOutputs[edge.source]) {
        // If specific handles are defined, map source output port -> target input port
        if (edge.sourceHandle && edge.targetHandle) {
          inputs[edge.targetHandle] = nodeOutputs[edge.source][edge.sourceHandle];
        } else {
          // If no specific handles, spread everything (fallback)
          Object.assign(inputs, nodeOutputs[edge.source]);
        }
      }
    }

    const handler = nodeRegistry[node.subtype];
    if (!handler) {
      throw new Error(`Handler missing for node subtype: ${node.subtype}`);
    }

    // Call the registry handler with its statically configured data and dynamic inputs
    const outputs = await handler(node.data || {}, inputs);
    nodeOutputs[nodeId] = outputs || {};
  }

  return nodeOutputs;
}
