import { WorkflowNode, WorkflowEdge } from '@flowscript/schema';
import { nodeRegistry } from './registry';
import { AutomationEnvironment, WorkflowContext } from './environment';
import { VariableResolver } from './utils/variableResolver';

/**
 * Executes a workflow graph starting from a specific trigger node.
 * Performs a topological sort and calls handlers in the registry for each node.
 * 
 * @param nodes All nodes in the workflow
 * @param edges All edges connecting nodes
 * @param startNodeId The ID of the node that triggered the execution
 * @param workflowId The ID of the workflow being executed
 * @param initialOutputs Output data from the trigger node itself (e.g., event data)
 * @param env The automation environment (DI)
 * @returns Map of node outputs
 */
export async function executeWorkflow(
  nodes: WorkflowNode[],
  edges: WorkflowEdge[],
  startNodeId: string,
  workflowId: string,
  initialOutputs: Record<string, any> = {},
  env: AutomationEnvironment
): Promise<Record<string, Record<string, any>>> {
  // Collect outputs generated by each node
  const nodeOutputs: Record<string, Record<string, any>> = {
    [startNodeId]: initialOutputs
  };

  const nodeMap = new Map<string, WorkflowNode>();
  const aliasMap = new Map<string, string>(); // nodeId -> alias
  const adjacencyList = new Map<string, string[]>();

  for (const node of nodes) {
    nodeMap.set(node.id, node);
    const alias = node.alias || node.data?.alias || `Node_${node.id.slice(0, 4)}`;
    aliasMap.set(node.id, alias);
    adjacencyList.set(node.id, []);
  }

  const getDownstreamNodesReachable = (startId: string): Set<string> => {
    const downstream = new Set<string>();
    const queue = [startId];
    while (queue.length > 0) {
      const cur = queue.shift()!;
      for (const neighbor of adjacencyList.get(cur) || []) {
        if (!downstream.has(neighbor)) {
          downstream.add(neighbor);
          queue.push(neighbor);
        }
      }
    }
    return downstream;
  };

  // Build the graph representing node -> children based on active nodes
  for (const edge of edges) {
    if (adjacencyList.has(edge.source) && nodeMap.has(edge.target)) {
      adjacencyList.get(edge.source)!.push(edge.target);
    }
  }

  // 1. Gather all nodes reachable from startNodeId
  const reachableNodes = new Set<string>();
  const queue = [startNodeId];
  reachableNodes.add(startNodeId);

  while (queue.length > 0) {
    const cur = queue.shift()!;
    for (const neighbor of adjacencyList.get(cur) || []) {
      if (!reachableNodes.has(neighbor)) {
        reachableNodes.add(neighbor);
        queue.push(neighbor);
      }
    }
  }

  // 1b. Add implicit edges for loop dependencies
  // Find all loop nodes (staticTable) in reachableNodes
  const loopNodes = Array.from(reachableNodes).filter(nid => nodeMap.get(nid)?.subtype === 'staticTable');
  const implicitEdges: { source: string; target: string }[] = [];

  const getAncestors = (startId: string): Set<string> => {
    const ancestors = new Set<string>();
    const ancestorQueue = [startId];
    while (ancestorQueue.length > 0) {
      const cur = ancestorQueue.shift()!;
      const incoming = edges.filter(e => e.target === cur);
      for (const edge of incoming) {
        if (!ancestors.has(edge.source)) {
          ancestors.add(edge.source);
          ancestorQueue.push(edge.source);
        }
      }
    }
    return ancestors;
  };

  const addedImplicit = new Set<string>();
  for (const tId of loopNodes) {
    const downstreamSet = getDownstreamNodesReachable(tId);
    const tableAncestors = getAncestors(tId);
    for (const dId of downstreamSet) {
      if (dId === tId) continue;
      const ancestors = getAncestors(dId);
      for (const bId of ancestors) {
        if (bId !== tId && !downstreamSet.has(bId) && !tableAncestors.has(bId) && reachableNodes.has(bId)) {
          const key = `${bId}->${tId}`;
          if (!addedImplicit.has(key)) {
            addedImplicit.add(key);
            implicitEdges.push({ source: bId, target: tId });
          }
        }
      }
    }
  }

  for (const ie of implicitEdges) {
    const list = adjacencyList.get(ie.source);
    if (list && !list.includes(ie.target)) {
      list.push(ie.target);
    }
  }

  // 2. Compute in-degrees for reachable subgraph only
  const inDegree = new Map<string, number>();
  for (const node of reachableNodes) {
    inDegree.set(node, 0);
  }

  for (const edge of edges) {
    if (reachableNodes.has(edge.source) && reachableNodes.has(edge.target)) {
      inDegree.set(edge.target, (inDegree.get(edge.target) || 0) + 1);
    }
  }

  for (const ie of implicitEdges) {
    inDegree.set(ie.target, (inDegree.get(ie.target) || 0) + 1);
  }

  // 3. Topological Sort (Kahn's Algorithm)
  const topoQueue: string[] = [];
  for (const [nodeId, degree] of inDegree.entries()) {
    if (degree === 0) {
      topoQueue.push(nodeId);
    }
  }

  const sortedNodes: string[] = [];
  while (topoQueue.length > 0) {
    const curId = topoQueue.shift()!;
    sortedNodes.push(curId);
    for (const neighbor of adjacencyList.get(curId) || []) {
      if (reachableNodes.has(neighbor)) {
        const newDegree = inDegree.get(neighbor)! - 1;
        inDegree.set(neighbor, newDegree);
        if (newDegree === 0) {
          topoQueue.push(neighbor);
        }
      }
    }
  }

  if (sortedNodes.length !== reachableNodes.size) {
    throw new Error('Cycle detected in workflow graph');
  }

  // 4. Pre-flight: Check if any node requires native debugger
  let debuggerAttached = false;
  const hasNativeNode = nodes.some(n => 
    n.data?.isNative || 
    n.subtype === 'pressKey' || 
    n.type === 'conditionalNode' ||
    (reachableNodes.has(n.id) && n.subtype === 'dynamicForm' && (n.data?.globalNative || (n.data?.mappings || []).some((m: any) => m.isNative)))
  );

  if (hasNativeNode) {
    console.log('[Flowscript] Native nodes detected, attaching debugger...');
    try {
      const response = await env.sendMessage({ type: 'DEBUGGER_ATTACH' });
      if (response && !response.success) {
        throw new Error(`Failed to attach debugger: ${response.error}`);
      }
      debuggerAttached = true;
      // Small grace period for debugger to settle
      await new Promise(r => setTimeout(r, 500));
    } catch (err: any) {
      console.error('[Flowscript] Debugger attachment failed:', err);
      throw new Error(`Debugger attachment failed: ${err.message}`);
    }
  }

  // 5. Initialize Workflow Context
  const secretsResponse = await env.sendMessage({ type: 'GET_LOCAL_SECRETS' }).catch(() => ({ secrets: {} }));
  
  const context: WorkflowContext = {
    nodes: {},
    trigger: initialOutputs,
    secrets: secretsResponse?.secrets || {},
    env: {
      url: env.url || '',
      browser: (typeof navigator !== 'undefined' && (navigator as any).userAgentData) 
        ? (navigator as any).userAgentData.brands[0].brand 
        : (typeof navigator !== 'undefined' ? (navigator.userAgent.includes('Chrome') ? 'Chrome' : 'Unknown') : 'Unknown'),
      platform: typeof navigator !== 'undefined' ? navigator.platform : 'unknown'
    }
  };

  // 6. Iterate over sorted nodes and execute
  const deadEdges = new Set<string>();
  for (const edge of edges) {
    if (!reachableNodes.has(edge.source)) {
      deadEdges.add(edge.id);
    }
  }

  const runNodeList = async (
    subNodes: string[],
    currentDeadEdges: Set<string>,
    loopNodeId?: string,
    iterationIndex?: number,
    iterationTotal?: number
  ) => {
    const executedInSub = new Set<string>();
    for (const nodeId of subNodes) {
      if (env.isAborted?.()) {
        throw new Error('Workflow execution stopped by user');
      }

      if (executedInSub.has(nodeId)) continue;
      executedInSub.add(nodeId);

      const node = nodeMap.get(nodeId)!;

      // Trigger node output is already provided by the caller
      if (nodeId === startNodeId || node.type === 'triggerNode') {
        continue;
      }

      const incomingEdges = edges.filter(e => e.target === nodeId);

      if (incomingEdges.length > 0 && incomingEdges.every(e => currentDeadEdges.has(e.id))) {
        const outgoingEdges = edges.filter(e => e.source === nodeId);
        outgoingEdges.forEach(e => currentDeadEdges.add(e.id));
        continue;
      }

      // Collect upstream port values
      const inputs: Record<string, any> = {};

      for (const edge of incomingEdges) {
        if (nodeOutputs[edge.source]) {
          // If specific handles are defined, map source output port -> target input port
          if (edge.sourceHandle && edge.targetHandle) {
            inputs[edge.targetHandle] = nodeOutputs[edge.source][edge.sourceHandle];
          } else {
            // If no specific handles, spread everything (fallback)
            Object.assign(inputs, nodeOutputs[edge.source]);
          }
        }
      }

      const handler = nodeRegistry[node.subtype];
      if (!handler) {
        throw new Error(`Handler missing for node subtype: ${node.subtype}`);
      }

      // Update context with latest node outputs mapped by BOTH alias and nodeId
      for (const [nid, outputs] of Object.entries(nodeOutputs)) {
        const n = nodeMap.get(nid);
        if (n?.subtype === 'staticTable') {
          if (context.nodes[nid] && '$index' in context.nodes[nid]) {
            continue;
          }
        }

        context.nodes[nid] = outputs;
        const alias = aliasMap.get(nid);
        if (alias) {
          if (context.nodes[alias] && '$index' in context.nodes[alias]) {
            continue;
          }
          context.nodes[alias] = outputs;
        }
      }

      // Resolve variables in node.data
      const resolvedData = VariableResolver.resolveDeep(node.data || {}, context);
      console.log(`[Flowscript] Executing ${node.subtype} with resolved data:`, resolvedData);

      if (env.onStateChange) {
        env.onStateChange({
          workflowId,
          status: 'running',
          currentNodeId: nodeId,
          loopProgress: loopNodeId !== undefined && iterationIndex !== undefined && iterationTotal !== undefined
            ? { nodeId: loopNodeId, index: iterationIndex, total: iterationTotal }
            : undefined
        });
      }

      env.onLog?.(`Executing node: ${node.subtype} (${aliasMap.get(nodeId) || nodeId})`, {
        iterationIndex,
        iterationTotal
      });

      try {
        if (node.subtype === 'staticTable') {
          const downstreamSet = getDownstreamNodesReachable(nodeId);
          const downstreamSorted = subNodes.filter(id => downstreamSet.has(id));

          downstreamSorted.forEach(id => executedInSub.add(id));

          const outputs = await handler(resolvedData, inputs, { 
            workflowId, 
            env,
            variables: context
          });
          nodeOutputs[nodeId] = outputs || [];

          const rows = Array.isArray(outputs) ? outputs : (resolvedData.rows || []);
          const total = rows.length;

          env.onLog?.(`Static Table loaded ${total} rows. Starting loop.`, {
            iterationIndex,
            iterationTotal
          });

          for (let idx = 0; idx < total; idx++) {
            if (env.isAborted?.()) {
              throw new Error('Workflow execution stopped by user');
            }

            const row = rows[idx];
            context.nodes[nodeId] = { ...row, $index: idx, $total: total };
            const alias = aliasMap.get(nodeId);
            if (alias) {
              context.nodes[alias] = { ...row, $index: idx, $total: total };
            }

            env.onLog?.(`Processing row ${idx + 1} of ${total}`, {
              iterationIndex: idx,
              iterationTotal: total
            });

            const iterationDeadEdges = new Set(currentDeadEdges);
            await runNodeList(downstreamSorted, iterationDeadEdges, nodeId, idx, total);
          }
          continue;
        }

        // Call the registry handler with its statically configured data, dynamic inputs, and execution context
        const outputs = await handler(resolvedData, inputs, { 
          workflowId, 
          env,
          variables: context
        });
        nodeOutputs[nodeId] = outputs || {};

        env.onLog?.(`Node ${node.subtype} executed successfully.`, {
          iterationIndex,
          iterationTotal
        });

        if (node.type === 'conditionalNode') {
          const conditionResult = outputs?.conditionResult;
          const outgoingEdges = edges.filter(e => e.source === nodeId);
          if (conditionResult === true) {
            // If true, kill the false branch
            outgoingEdges.filter(e => e.sourceHandle === 'false').forEach(e => currentDeadEdges.add(e.id));
          } else {
            // If false, kill the true branch
            outgoingEdges.filter(e => e.sourceHandle === 'true').forEach(e => currentDeadEdges.add(e.id));
          }
        }
      } catch (err: any) {
        env.onLog?.(`Node ${node.subtype} failed: ${err.message}`, {
          isError: true,
          iterationIndex,
          iterationTotal
        });
        throw err;
      }
    }
  };

  try {
    if (env.onStateChange) {
      env.onStateChange({
        workflowId,
        status: 'running',
        currentNodeId: startNodeId
      });
    }
    env.onLog?.('Starting workflow execution');

    await runNodeList(sortedNodes, deadEdges);

    if (env.onStateChange) {
      env.onStateChange({
        workflowId,
        status: 'completed'
      });
    }
    env.onLog?.('Workflow completed successfully.');
  } catch (err: any) {
    const isStopped = err.message === 'Workflow execution stopped by user' || env.isAborted?.();
    if (env.onStateChange) {
      env.onStateChange({
        workflowId,
        status: isStopped ? 'stopped' : 'failed'
      });
    }
    env.onLog?.(isStopped ? 'Workflow execution stopped.' : `Workflow failed: ${err.message}`, {
      isError: !isStopped
    });
    throw err;
  } finally {
    if (debuggerAttached) {
      console.log('[Flowscript] Detaching debugger...');
      await env.sendMessage({ type: 'DEBUGGER_DETACH' }).catch((err: any) => {
        console.error('[Flowscript] Failed to detach debugger:', err);
      });
    }
  }

  return nodeOutputs;
}
